<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LabelSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('labels')->insert([
            [
                'id' => 2,
                'name' => 'Print Outdoor',
                'type' => 'standart',
                'desc' => 'MMT & Stiker dibawah 1M tetap dihitung 1 M2, MMT Mata Ikan Standar 4pcs, lebih dari itu dihitung 500 per lubang, MMT khusus rontek lebihan 7 cm atas bawah + biaya 1 rb/lembar',
                'size' => '1',
                'unit' => '4',
                'created_at' => '2025-05-27 04:20:42',
                'updated_at' => '2025-06-04 09:03:48',
            ],
            [
                'id' => 9,
                'name' => 'Print Indoor',
                'type' => 'standart',
                'desc' => null,
                'size' => '1',
                'unit' => '5',
                'created_at' => '2025-05-29 08:08:27',
                'updated_at' => '2025-05-29 08:19:10',
            ],
            [
                'id' => 11,
                'name' => 'A3',
                'type' => 'standart',
                'desc' => null,
                'size' => '1',
                'unit' => '6',
                'created_at' => '2025-05-29 01:27:11',
                'updated_at' => '2025-05-29 01:27:11',
            ],
            [
                'id' => 14,
                'name' => 'Finishing MMT',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-05 12:12:49',
                'updated_at' => '2025-06-07 18:23:59',
            ],
            [
                'id' => 15,
                'name' => 'Print DTF Kain',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-07 18:26:18',
                'updated_at' => '2025-06-07 18:26:18',
            ],
            [
                'id' => 16,
                'name' => 'Paket Brosur',
                'type' => 'standart',
                'desc' => null,
                'size' => '500',
                'unit' => '6',
                'created_at' => '2025-06-07 18:48:28',
                'updated_at' => '2025-06-07 18:48:28',
            ],
            [
                'id' => 17,
                'name' => 'Paker X & Roll Banner',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-07 18:57:56',
                'updated_at' => '2025-06-07 18:57:56',
            ],
            [
                'id' => 18,
                'name' => 'Paker Kartu Nama',
                'type' => 'standart',
                'desc' => '1 pac isi 100pcs, paket sudah termasuk biaya potong dan box mika, laminasi gloss/doff 1 sisi + 10 rb/box',
                'size' => '1',
                'unit' => '0',
                'created_at' => '2025-06-07 19:19:12',
                'updated_at' => '2025-06-07 19:22:23',
            ],
            [
                'id' => 19,
                'name' => 'Finishing Kartu Nama',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-07 19:23:43',
                'updated_at' => '2025-06-07 19:23:43',
            ],
            [
                'id' => 20,
                'name' => 'Biaya Edit',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-07 19:24:41',
                'updated_at' => '2025-06-07 19:24:41',
            ],
            [
                'id' => 21,
                'name' => 'Amplop',
                'type' => 'standart',
                'desc' => 'Per pack isi 100 lembar, harga untuk 1 warna hitam, tambah warna 25 rb/ warna',
                'size' => '100',
                'unit' => '6',
                'created_at' => '2025-06-07 19:28:08',
                'updated_at' => '2025-06-07 19:28:08',
            ],
            [
                'id' => 22,
                'name' => 'Finishing Amplop',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-07 19:28:35',
                'updated_at' => '2025-06-07 19:28:35',
            ],
            [
                'id' => 23,
                'name' => 'Kop Surat',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-07 19:30:47',
                'updated_at' => '2025-06-07 19:30:47',
            ],
            [
                'id' => 24,
                'name' => 'Finishing Potong',
                'type' => 'standart',
                'desc' => null,
                'size' => '1',
                'unit' => '8',
                'created_at' => '2025-06-07 19:32:01',
                'updated_at' => '2025-06-07 19:47:10',
            ],
            [
                'id' => 25,
                'name' => 'Finishing Cutting',
                'type' => 'standart',
                'desc' => null,
                'size' => '1',
                'unit' => '8',
                'created_at' => '2025-06-07 19:32:56',
                'updated_at' => '2025-06-07 19:43:22',
            ],
            [
                'id' => 26,
                'name' => 'Laminasi',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-07 19:49:32',
                'updated_at' => '2025-06-07 19:49:32',
            ],
            [
                'id' => 27,
                'name' => 'Cutting',
                'type' => 'standart',
                'desc' => null,
                'size' => null,
                'unit' => '0',
                'created_at' => '2025-06-07 19:53:20',
                'updated_at' => '2025-06-07 19:53:20',
            ],
            [
                'id' => 33,
                'name' => 'Print Outdoor 2',
                'type' => 'standart',
                'desc' => null,
                'size' => '1',
                'unit' => '0',
                'created_at' => '2025-06-12 23:16:12',
                'updated_at' => '2025-06-12 23:16:12',
            ],
        ]);
    }
}
